// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_home
void ui_home_screen_init(void);
lv_obj_t * ui_home;
void ui_event_buttonPvP(lv_event_t * e);
lv_obj_t * ui_buttonPvP;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label2;
void ui_event_Image3(lv_event_t * e);
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image30;
lv_obj_t * ui_Image31;
lv_obj_t * ui_Image32;
lv_obj_t * ui_Image33;
lv_obj_t * ui_Image34;
lv_obj_t * ui_Image35;
lv_obj_t * ui_Image36;
lv_obj_t * ui_Image37;
lv_obj_t * ui_Image38;
lv_obj_t * ui_Image39;
lv_obj_t * ui_Label3;
// CUSTOM VARIABLES


// SCREEN: ui_settings
void ui_settings_screen_init(void);
lv_obj_t * ui_settings;
// CUSTOM VARIABLES


// SCREEN: ui_playPage1
void ui_playPage1_screen_init(void);
void card_init(void);
lv_obj_t * ui_playPage1;
void getStart(lv_event_t * e);
lv_obj_t * ui_Start;
lv_obj_t * ui_Label_start;
void ui_event_Image4(lv_event_t * e);
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Image26;
lv_obj_t * p1_cards[10];
lv_obj_t * p2_cards[10];
lv_obj_t * curr_player_label;


// SCREEN: ui_playPage2
void ui_playPage2_screen_init(void);
lv_obj_t * ui_playPage2;
lv_obj_t * ui_Button1;
void ui_event_Image8(lv_event_t * e);
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image11;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_home_v[1] = {&ui_img_home_2v2_png};
const lv_img_dsc_t * ui_imgset_card_[2] = {&ui_img_card_1_png, &ui_img_card_3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_buttonPvP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_playPage1, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_playPage1_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_playPage2, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_playPage2_screen_init);
    }
}

void ui_event_Image3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_settings_screen_init);
    }
}

void ui_event_Image4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_home_screen_init);
    }
}

void ui_event_Image8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_home_screen_init);
    }
}

void getStart(lv_event_t * e) 
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        card_init();
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_home_screen_init();
    ui_settings_screen_init();
    ui_playPage1_screen_init();
    ui_playPage2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_home);
}
