// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void sendSerialData(char * data);


// SCREEN: ui_home
void ui_home_screen_init(void);
extern lv_obj_t * ui_home;
void ui_event_buttonPvP(lv_event_t * e);
extern lv_obj_t * ui_buttonPvP;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_Image36;
extern lv_obj_t * ui_Image37;
extern lv_obj_t * ui_Image38;
extern lv_obj_t * ui_Image39;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_settings
void ui_settings_screen_init(void);
extern lv_obj_t * ui_settings;
// CUSTOM VARIABLES

// SCREEN: ui_playPage1
void ui_playPage1_screen_init(void);
void card_init(void);
extern lv_obj_t * ui_playPage1;
extern lv_obj_t * endTag;
void getStart(lv_event_t * e);
extern lv_obj_t * ui_Start;
extern lv_obj_t * ui_Label_start;
void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * p1_cards[10];
extern lv_obj_t * p2_cards[10];
extern lv_obj_t * curr_player_label;
extern lv_obj_t * prev_card_label;
extern lv_obj_t * op_confirm_button;
extern lv_obj_t * op_confirm_label;
extern lv_obj_t * op_cancel_button;
extern lv_obj_t * op_cancel_label;
extern lv_obj_t * op_pass_button;
extern lv_obj_t * op_pass_label;
// CUSTOM VARIABLES

// SCREEN: ui_playPage2
void ui_playPage2_screen_init(void);
extern lv_obj_t * ui_playPage2;
extern lv_obj_t * ui_Button1;
void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_home_png);
LV_IMG_DECLARE(ui_img_play_bg_png);
LV_IMG_DECLARE(ui_img_home_2v2_png);    // assets/home_2v2.png
LV_IMG_DECLARE(ui_img_home_cpu_png);    // assets/home_cpu.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_814085921);    // assets/像素-星球.png
LV_IMG_DECLARE(ui_img_1993502234);    // assets/像素_树.png
LV_IMG_DECLARE(ui_img_1452054505);    // assets/像素_草莓.png
LV_IMG_DECLARE(ui_img_49543422);    // assets/吃豆子.png
LV_IMG_DECLARE(ui_img_1144387654);    // assets/像素_房子.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_loader_png);    // assets/loader.png
LV_IMG_DECLARE(ui_img_famer_png);    // assets/famer.png
LV_IMG_DECLARE(ui_img_vs_png);    // assets/vs.png
LV_IMG_DECLARE(ui_img_card_1_png);  // card 1
LV_IMG_DECLARE(ui_img_card_2_png);  // card 2 
LV_IMG_DECLARE(ui_img_card_3_png);  // card3
LV_IMG_DECLARE(ui_img_card_4_png);
LV_IMG_DECLARE(ui_img_card_5_png);
LV_IMG_DECLARE(ui_img_card_6_png);
LV_IMG_DECLARE(ui_img_card_7_png);
LV_IMG_DECLARE(ui_img_card_8_png);
LV_IMG_DECLARE(ui_img_card_9_png);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
