// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_home
void ui_home_screen_init(void);
extern lv_obj_t * ui_home;
void ui_event_buttonPvP(lv_event_t * e);
extern lv_obj_t * ui_buttonPvP;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_Image36;
extern lv_obj_t * ui_Image37;
extern lv_obj_t * ui_Image38;
extern lv_obj_t * ui_Image39;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_settings
void ui_settings_screen_init(void);
extern lv_obj_t * ui_settings;
// CUSTOM VARIABLES

// SCREEN: ui_playPage1
void ui_playPage1_screen_init(void);
extern lv_obj_t * ui_playPage1;
void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image41;
extern lv_obj_t * ui_Image43;
extern lv_obj_t * ui_Image44;
extern lv_obj_t * ui_Image45;
extern lv_obj_t * ui_Image46;
extern lv_obj_t * ui_Image47;
extern lv_obj_t * ui_Image48;
extern lv_obj_t * ui_Image40;
extern lv_obj_t * ui_Image42;
// CUSTOM VARIABLES

// SCREEN: ui_playPage2
void ui_playPage2_screen_init(void);
extern lv_obj_t * ui_playPage2;
extern lv_obj_t * ui_Button1;
void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1572002003);    // assets/home_bg (2).png
LV_IMG_DECLARE(ui_img_home_2v2_png);    // assets/home_2v2.png
LV_IMG_DECLARE(ui_img_home_cpu_png);    // assets/home_cpu.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_814085921);    // assets/像素-星球.png
LV_IMG_DECLARE(ui_img_1993502234);    // assets/像素_树.png
LV_IMG_DECLARE(ui_img_1452054505);    // assets/像素_草莓.png
LV_IMG_DECLARE(ui_img_49543422);    // assets/吃豆子.png
LV_IMG_DECLARE(ui_img_1144387654);    // assets/像素_房子.png
LV_IMG_DECLARE(ui_img_play_bg_png);    // assets/play_bg.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_loader_png);    // assets/loader.png
LV_IMG_DECLARE(ui_img_famer_png);    // assets/famer.png
LV_IMG_DECLARE(ui_img_vs_png);    // assets/vs.png
LV_IMG_DECLARE(ui_img_card_2_png);    // assets/card_2.png
LV_IMG_DECLARE(ui_img_card_4_png);    // assets/card_4.png
LV_IMG_DECLARE(ui_img_card_5_png);    // assets/card_5.png
LV_IMG_DECLARE(ui_img_card_6_png);    // assets/card_6.png
LV_IMG_DECLARE(ui_img_card_7_png);    // assets/card_7.png
LV_IMG_DECLARE(ui_img_card_8_png);    // assets/card_8.png
LV_IMG_DECLARE(ui_img_card_9_png);    // assets/card_9.png
LV_IMG_DECLARE(ui_img_card_1_png);    // assets/card_1.png
LV_IMG_DECLARE(ui_img_card_3_png);    // assets/card_3.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
