// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// 初始化屏幕
void ui_playPage1_screen_init(void)
{
    ui_playPage1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_playPage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_playPage1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 开始游戏按钮
    ui_Start = lv_btn_create(ui_playPage1);
    lv_obj_set_width(ui_Start, 160);
    lv_obj_set_height(ui_Start, 60);
    lv_obj_set_x(ui_Start, 0);  // 位于屏幕中心
    lv_obj_set_y(ui_Start, 0);
    lv_obj_set_align(ui_Start, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Start, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_start = lv_label_create(ui_playPage1);
    lv_obj_set_width(ui_Label_start, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_start, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_start, 0);
    lv_obj_set_y(ui_Label_start, 0);
    lv_obj_set_align(ui_Label_start, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_start, "Start");
    lv_obj_set_style_text_color(ui_Label_start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_start, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image4, &ui_img_back_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image4, -371);
    lv_obj_set_y(ui_Image4, -203);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 350);

    ui_Image6 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image6, &ui_img_loader_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image6, 53);
    lv_obj_set_y(ui_Image6, -212);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 220);

    ui_Image7 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image7, &ui_img_famer_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image7, -54);
    lv_obj_set_y(ui_Image7, -214);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image5, &ui_img_vs_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image5, -3);
    lv_obj_set_y(ui_Image5, -212);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    
    // 添加事件
    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Start, getStart, LV_EVENT_ALL, NULL);

}

// 卡牌初始化
void card_init(void) 
{

    // 销毁开始按钮
    lv_obj_del(ui_Start)

    ui_img_card_1 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_1, &ui_img_card_1_png);
    lv_obj_set_width(ui_img_card_1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_1, -360);
    lv_obj_set_y(ui_img_card_1, 170);
    lv_obj_set_align(ui_img_card_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_card_2 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_2, &ui_img_card_2_png);
    lv_obj_set_width(ui_img_card_2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_2, -280);
    lv_obj_set_y(ui_img_card_2, 170);
    lv_obj_set_align(ui_img_card_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_card_3 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_3, &ui_img_card_3_png);
    lv_obj_set_width(ui_img_card_3, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_3, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_3, -200);
    lv_obj_set_y(ui_img_card_3, 170);
    lv_obj_set_align(ui_img_card_3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_card_4 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_4, &ui_img_card_4_png);
    lv_obj_set_width(ui_img_card_4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_4, -120);
    lv_obj_set_y(ui_img_card_4, 170);
    lv_obj_set_align(ui_img_card_4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_card_5 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_5, &ui_img_card_5_png);
    lv_obj_set_width(ui_img_card_5, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_5, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_5, -40);
    lv_obj_set_y(ui_img_card_5, 170);
    lv_obj_set_align(ui_img_card_5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_card_6 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_6, &ui_img_card_6_png);
    lv_obj_set_width(ui_img_card_6, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_6, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_6, 40);
    lv_obj_set_y(ui_img_card_6, 170);
    lv_obj_set_align(ui_img_card_6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_card_7 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_7, &ui_img_card_7_png);
    lv_obj_set_width(ui_img_card_7, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_7, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_7, 120);
    lv_obj_set_y(ui_img_card_7, 170);
    lv_obj_set_align(ui_img_card_7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_card_8 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_8, &ui_img_card_8_png);
    lv_obj_set_width(ui_img_card_8, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_8, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_8, 200);
    lv_obj_set_y(ui_img_card_8, 170);
    lv_obj_set_align(ui_img_card_8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_card_9 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_9, &ui_img_card_9_png);
    lv_obj_set_width(ui_img_card_9, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_9, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_9, 280);
    lv_obj_set_y(ui_img_card_9, 170);
    lv_obj_set_align(ui_img_card_9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    ui_img_card_1 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_img_card_1, &ui_img_card_1_png);
    lv_obj_set_width(ui_img_card_1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_img_card_1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_img_card_1, 360);
    lv_obj_set_y(ui_img_card_1, 170);
    lv_obj_set_align(ui_img_card_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_card_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_card_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
}