// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

typedef struct
{
    int id;
    const lv_img_dsc_t *url;
    int val;
    int owner;
} cardObj;

// 声明 pendding_cards_p1 和 p1
#define MAX_PENDING_CARDS 10
#define DEFAULT_COLOR lv_color_hex(0x000000) // 表示使用默认主题
#define WHITE_COLOR lv_color_hex(0xFFFFFF)
#define RED_COLOR lv_color_hex(0xFF0000)
lv_obj_t *pendding_cards_p1[MAX_PENDING_CARDS];
int pendding_card_count_p1 = 0;
lv_obj_t *pendding_cards_p2[MAX_PENDING_CARDS];
int pendding_card_count_p2 = 0;
int curr_player = 1; // 0 -> player1, 1 -> player2, 这里是 1 因为最开始需要调用一次 set_curr_player
char prevCardStr[10] = "";

// 提前声明函数
void card_init(void);
void p1_card_select(lv_event_t *e);
void p2_card_select(lv_event_t *e);
void set_curr_player(void);
void set_op_panel(void);
void set_op_button(void);
void set_prev_card(void);
void set_button(lv_obj_t **target, lv_obj_t **label, int x, int y, const char *text, lv_color_t bg_color, lv_color_t text_color, lv_event_cb_t function);
void confirm(void);
void cancel(void);
void pass(void);
void confirm_p1_cards(void);
void confirm_p2_cards(void);

cardObj card_images_1[] = {
    {0, &ui_img_card_9_png, 9, 0},
    {1, &ui_img_card_9_png, 9, 0},
    {2, &ui_img_card_7_png, 7, 0},
    {3, &ui_img_card_6_png, 6, 0},
    {4, &ui_img_card_5_png, 5, 0},
    {5, &ui_img_card_5_png, 5, 0},
    {6, &ui_img_card_4_png, 4, 0},
    {7, &ui_img_card_3_png, 3, 0},
    {8, &ui_img_card_1_png, 1, 0},
    {9, &ui_img_card_1_png, 1, 0},
    {10, &ui_img_card_9_png, 9, 1},
    {11, &ui_img_card_8_png, 8, 1},
    {12, &ui_img_card_7_png, 7, 1},
    {13, &ui_img_card_6_png, 6, 1},
    {14, &ui_img_card_5_png, 5, 1},
    {15, &ui_img_card_5_png, 5, 1},
    {16, &ui_img_card_4_png, 4, 1},
    {17, &ui_img_card_3_png, 3, 1},
    {18, &ui_img_card_3_png, 3, 1},
    {19, &ui_img_card_2_png, 2, 1}};

// 初始化屏幕
void ui_playPage1_screen_init(void)
{
    ui_playPage1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_playPage1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_playPage1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 添加背景图
    lv_obj_t *ui_background = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_background, &ui_img_play_bg_png);
    lv_obj_set_width(ui_background, LV_PCT(100));             // 宽度 100% 父对象
    lv_obj_set_height(ui_background, LV_PCT(100));            // 高度 100% 父对象
    lv_obj_align(ui_background, LV_ALIGN_CENTER, 0, 0);       // 居中对齐
    lv_obj_clear_flag(ui_background, LV_OBJ_FLAG_SCROLLABLE); // 禁用滚动

    creat_start_button();

    ui_Image4 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image4, &ui_img_back_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);  /// 32
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT); /// 32
    lv_obj_set_x(ui_Image4, -371);
    lv_obj_set_y(ui_Image4, -203);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);                        /// Flags
    lv_img_set_zoom(ui_Image4, 350);

    ui_Image6 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image6, &ui_img_loader_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);  /// 32
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT); /// 32
    lv_obj_set_x(ui_Image6, 53);
    lv_obj_set_y(ui_Image6, -212);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_Image6, 220);

    ui_Image7 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image7, &ui_img_famer_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);  /// 32
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT); /// 32
    lv_obj_set_x(ui_Image7, -54);
    lv_obj_set_y(ui_Image7, -214);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image5 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image5, &ui_img_vs_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);  /// 32
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT); /// 32
    lv_obj_set_x(ui_Image5, -3);
    lv_obj_set_y(ui_Image5, -212);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // 添加事件
    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
}

// 卡牌初始化
void card_init(void)
{
    // 销毁开始按钮
    clean_start_button();
    /*
        在两幅牌中间区域添加
        1. 当前玩家
        2. 按钮：pass cancel confirm，
        3. 上轮的玩家出牌
    */
    set_op_panel();
    init_p1_card(170);
    init_p2_card(-120);
}

// 创建开始按钮
void creat_start_button(void)
{
    ui_Start = lv_btn_create(ui_playPage1);
    lv_obj_set_width(ui_Start, 160);
    lv_obj_set_height(ui_Start, 60);
    lv_obj_set_x(ui_Start, 0); // 位于屏幕中心
    lv_obj_set_y(ui_Start, 0);
    lv_obj_set_align(ui_Start, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Start, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Start, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Label_start = lv_label_create(ui_playPage1);
    lv_obj_set_width(ui_Label_start, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label_start, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label_start, 0);
    lv_obj_set_y(ui_Label_start, 0);
    lv_obj_set_align(ui_Label_start, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_start, "Start");
    lv_obj_set_style_text_color(ui_Label_start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_start, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Start, getStart, LV_EVENT_CLICKED, NULL);
}

// 销毁开始按钮
void clean_start_button(void)
{
    lv_obj_del(ui_Start);
    lv_obj_del(ui_Label_start);
}

// 初始化 p1 的卡牌
void init_p1_card(int y)
{
    for (int i = 0; i < 10; i++)
    {
        p1_cards[i] = lv_img_create(ui_playPage1);
        lv_img_set_src(p1_cards[i], card_images_1[i].url);
        lv_obj_set_user_data(p1_cards[i], &card_images_1[i]); // 设置用户数据
        lv_obj_set_width(p1_cards[i], LV_SIZE_CONTENT);
        lv_obj_set_height(p1_cards[i], LV_SIZE_CONTENT);
        lv_obj_set_x(p1_cards[i], -360 + i * 80);
        lv_obj_set_y(p1_cards[i], y);
        lv_obj_set_align(p1_cards[i], LV_ALIGN_CENTER);
        lv_obj_add_flag(p1_cards[i], LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);
        lv_obj_clear_flag(p1_cards[i], LV_OBJ_FLAG_SCROLLABLE);
        // 为每个卡片添加点击事件
        lv_obj_add_event_cb(p1_cards[i], p1_card_select, LV_EVENT_CLICKED, NULL);
    }
}

// 初始化 p2 的卡牌
void init_p2_card(int y)
{
    for (int i = 0; i < 10; i++)
    {
        p2_cards[i] = lv_img_create(ui_playPage1);
        lv_img_set_src(p2_cards[i], card_images_1[i + 10].url);
        lv_obj_set_user_data(p2_cards[i], &card_images_1[i + 10]); // 修正用户数据设置
        lv_obj_set_width(p2_cards[i], LV_SIZE_CONTENT);
        lv_obj_set_height(p2_cards[i], LV_SIZE_CONTENT);
        lv_obj_set_x(p2_cards[i], -360 + i * 80);
        lv_obj_set_y(p2_cards[i], y);
        lv_obj_set_align(p2_cards[i], LV_ALIGN_CENTER);
        lv_obj_add_flag(p2_cards[i], LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);
        lv_obj_clear_flag(p2_cards[i], LV_OBJ_FLAG_SCROLLABLE);
        // 为每个卡片添加点击事件
        lv_obj_add_event_cb(p2_cards[i], p2_card_select, LV_EVENT_CLICKED, NULL);
    }
}

// p1 选择卡片
void p1_card_select(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED && curr_player == 0)
    {
        lv_obj_t *obj = lv_event_get_target(e);

        // 检查卡片是否在 pendding_cards_p1 数组中
        int found_index = -1;
        for (int i = 0; i < pendding_card_count_p1; i++)
        {
            if (pendding_cards_p1[i] == obj)
            {
                found_index = i;
                break;
            }
        }

        if (found_index != -1)
        {
            // 卡片已在数组中，将其放回原来位置并从数组中移除
            for (int i = found_index; i < pendding_card_count_p1 - 1; i++)
            {
                pendding_cards_p1[i] = pendding_cards_p1[i + 1];
            }
            pendding_card_count_p1--;
            lv_obj_set_y(obj, 170);
        }
        else
        {
            lv_obj_set_y(obj, 150);
            if (pendding_card_count_p1 < MAX_PENDING_CARDS)
            {
                pendding_cards_p1[pendding_card_count_p1++] = obj;
            }
        }
    }
}

// p2 选择卡片
void p2_card_select(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED && curr_player == 1)
    {
        lv_obj_t *obj = lv_event_get_target(e);

        // 检查卡片是否在 pendding_cards_p2 数组中
        int found_index = -1;
        for (int i = 0; i < pendding_card_count_p2; i++)
        {
            if (pendding_cards_p2[i] == obj)
            {
                found_index = i;
                break;
            }
        }

        if (found_index != -1)
        {
            // 卡片已在数组中，将其放回原来位置并从数组中移除
            for (int i = found_index; i < pendding_card_count_p2 - 1; i++)
            {
                pendding_cards_p2[i] = pendding_cards_p2[i + 1];
            }
            pendding_card_count_p2--;
            lv_obj_set_y(obj, -120);
        }
        else
        {
            lv_obj_set_y(obj, -100);
            if (pendding_card_count_p2 < MAX_PENDING_CARDS)
            {
                pendding_cards_p2[pendding_card_count_p2++] = obj;
            }
        }
    }
}

// 创建中间的操作面板
void set_op_panel(void)
{
    set_op_button();
    set_curr_player();
    set_prev_card();
}

// 设置之前出牌
void set_prev_card(void) 
{
    if (prev_card_label == NULL)
    {
        // 如果标签不存在，创建新的标签
        prev_card_label = lv_label_create(ui_playPage1);
        lv_obj_set_width(prev_card_label, LV_SIZE_CONTENT);
        lv_obj_set_height(prev_card_label, LV_SIZE_CONTENT);
        lv_obj_set_x(prev_card_label, 340);
        lv_obj_set_y(prev_card_label, 25);
        lv_obj_set_align(prev_card_label, LV_ALIGN_CENTER);
        lv_obj_set_style_text_color(prev_card_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(prev_card_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    // 更新标签文本
    lv_label_set_text(prev_card_label, prevCardStr);
}

// 设置操作按钮
void set_op_button(void)
{
    if (op_confirm_button)
        lv_obj_del(op_confirm_button);
    if (op_cancel_button)
        lv_obj_del(op_cancel_button);
    if (op_pass_button)
        lv_obj_del(op_pass_button);
    set_button(&op_confirm_button, &op_confirm_label, 160, 25, "confirm", DEFAULT_COLOR, WHITE_COLOR, confirm);
    set_button(&op_cancel_button, &op_cancel_label, 0, 25, "cancel", WHITE_COLOR, RED_COLOR, cancel);
    set_button(&op_pass_button, &op_pass_label, -160, 25, "pass", RED_COLOR, WHITE_COLOR, pass);
}

// set_button 函数
void set_button(lv_obj_t **target, lv_obj_t **label, int x, int y, const char *text, lv_color_t bg_color, lv_color_t text_color, lv_event_cb_t function)
{
    *target = lv_btn_create(ui_playPage1);
    lv_obj_set_width(*target, 100);
    lv_obj_set_height(*target, 50);
    lv_obj_set_x(*target, x);
    lv_obj_set_y(*target, y);
    lv_obj_set_align(*target, LV_ALIGN_CENTER);
    lv_obj_add_flag(*target, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(*target, LV_OBJ_FLAG_SCROLLABLE);
    // 设置按钮背景色（仅当非默认颜色时）
    if (bg_color.full != 0)
    { // 0表示使用默认主题色
        lv_obj_set_style_bg_color(*target, bg_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    *label = lv_label_create(ui_playPage1);
    lv_obj_set_width(*label, LV_SIZE_CONTENT);
    lv_obj_set_height(*label, LV_SIZE_CONTENT);
    lv_obj_set_x(*label, x);
    lv_obj_set_y(*label, y);
    lv_obj_set_align(*label, LV_ALIGN_CENTER);
    lv_label_set_text(*label, text);
    lv_obj_set_style_text_color(*label, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(*label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(*label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    if (function != NULL)
    {
        lv_obj_add_event_cb(*target, function, LV_EVENT_CLICKED, NULL);
    }
}

// 设置当前玩家
void set_curr_player(void)
{
    curr_player = (curr_player == 0) ? 1 : 0;

    if (curr_player_label == NULL)
    {
        // 如果标签不存在，创建新的标签
        curr_player_label = lv_label_create(ui_playPage1);
        lv_obj_set_width(curr_player_label, LV_SIZE_CONTENT);
        lv_obj_set_height(curr_player_label, LV_SIZE_CONTENT);
        lv_obj_set_x(curr_player_label, -340);
        lv_obj_set_y(curr_player_label, 25);
        lv_obj_set_align(curr_player_label, LV_ALIGN_CENTER);
        lv_obj_set_style_text_color(curr_player_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(curr_player_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    // 更新标签文本
    lv_label_set_text(curr_player_label, (curr_player == 0) ? "player_1" : "player_2");
}

// 按下 confirm 按钮
void confirm(void)
{
    int total;
    lv_obj_t **pendding_cards;
    if (curr_player == 0)
    {
        total = pendding_card_count_p1;
        pendding_cards = pendding_cards_p1;
    }
    else
    {
        total = pendding_card_count_p2;
        pendding_cards = pendding_cards_p2;
    }

    // 统计各牌值的数量
    int count[20] = {0};
    for (int i = 0; i < total; i++)
    {
        cardObj *obj = (cardObj *)lv_obj_get_user_data(pendding_cards[i]);
        count[obj->val]++;
    }

    // 验证牌型
    bool valid = false;
    memset(prevCardStr, 0, sizeof(prevCardStr)); // 清空之前的内容

    if (total == 1)
    { // 单张
        for (int i = 1; i <= 19; i++)
        {
            if (count[i] == 1)
            {
                sprintf(prevCardStr, "%d", i);
                valid = true;
                break;
            }
        }
    }
    else if (total == 2)
    { // 对子
        for (int i = 1; i <= 19; i++)
        {
            if (count[i] == 2)
            {
                sprintf(prevCardStr, "%d%d", i, i);
                valid = true;
                break;
            }
        }
    }
    else if (total == 4)
    { // 三带一
        int triple = -1, single = -1;
        for (int i = 1; i <= 19; i++)
        {
            if (count[i] == 3)
            {
                triple = i;
            }
            else if (count[i] == 1)
            {
                single = i;
            }
            else if (count[i] != 0)
            { // 存在非法数量
                break;
            }
        }
        if (triple != -1 && single != -1)
        {
            sprintf(prevCardStr, "%d%d%d%d", triple, triple, triple, single);
            valid = true;
        }
    }

    if (!valid)
    {
        cancel();
        return;
    }

    // 执行确认操作
    if (curr_player == 0)
    {
        confirm_p1_cards();
    }
    else
    {
        confirm_p2_cards();
    }
    set_prev_card();
    set_curr_player();
}

// 按下 cancel 按钮
void cancel(void)
{
    // 根据当前玩家处理对应的待处理卡牌数组
    if (curr_player == 0)
    {
        for (int i = 0; i < pendding_card_count_p1; i++)
        {
            lv_obj_set_y(pendding_cards_p1[i], 170);
        }
        pendding_card_count_p1 = 0;
    }
    else
    {
        for (int i = 0; i < pendding_card_count_p2; i++)
        {
            lv_obj_set_y(pendding_cards_p2[i], -120);
        }
        pendding_card_count_p2 = 0;
    }
}

// 按下 pass 按钮
void pass(void)
{
    cancel();
    memset(prevCardStr, 0, sizeof(prevCardStr));
    set_curr_player();
}

// 处理玩家一确认操作的函数
void confirm_p1_cards(void)
{
    int i = 0;
    while (i < pendding_card_count_p1)
    {
        lv_obj_t *card = pendding_cards_p1[i];
        if (!card)
        {
            i++;
            continue;
        }

        cardObj *obj = (cardObj *)lv_obj_get_user_data(card);
        if (obj)
        {
            obj->owner = -1; // 标记为已使用

            // 从p1_cards数组中移除
            for (int j = 0; j < 10; j++)
            {
                if (p1_cards[j] == card)
                {
                    p1_cards[j] = NULL;
                    break;
                }
            }
            lv_obj_del(card);            // 删除屏幕上的卡牌
            pendding_cards_p1[i] = NULL; // 置空指针
        }
        i++;
    }
    pendding_card_count_p1 = 0;                              // 清空计数器
    memset(pendding_cards_p1, 0, sizeof(pendding_cards_p1)); // 清空数组

    // 重新排列剩余卡牌
    int x = -360;
    int current_pos = 0;
    for (int j = 0; j < 10; j++)
    {
        if (p1_cards[j] != NULL)
        {
            lv_obj_set_x(p1_cards[j], x + current_pos * 80);
            current_pos++;
        }
    }
}

// 处理玩家二确认操作的函数
void confirm_p2_cards(void)
{
    int i = 0;
    while (i < pendding_card_count_p2)
    {
        lv_obj_t *card = pendding_cards_p2[i];
        if (!card)
        {
            i++;
            continue;
        }

        cardObj *obj = (cardObj *)lv_obj_get_user_data(card);
        if (obj)
        {
            obj->owner = -1; // 标记为已使用

            // 从p2_cards数组中移除
            for (int j = 0; j < 10; j++)
            {
                if (p2_cards[j] == card)
                {
                    p2_cards[j] = NULL;
                    break;
                }
            }
            lv_obj_del(card);            // 删除屏幕上的卡牌
            pendding_cards_p2[i] = NULL; // 置空指针
        }
        i++;
    }
    pendding_card_count_p2 = 0;                              // 清空计数器
    memset(pendding_cards_p2, 0, sizeof(pendding_cards_p2)); // 清空数组

    // 重新排列剩余卡牌
    int x = -360;
    int current_pos = 0;
    for (int j = 0; j < 10; j++)
    {
        if (p2_cards[j] != NULL)
        {
            lv_obj_set_x(p2_cards[j], x + current_pos * 80);
            current_pos++;
        }
    }
}