// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_home, &ui_img_1572002003, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonPvP = lv_btn_create(ui_home);
    lv_obj_set_width(ui_buttonPvP, 180);
    lv_obj_set_height(ui_buttonPvP, 60);
    lv_obj_set_x(ui_buttonPvP, -200);
    lv_obj_set_y(ui_buttonPvP, 120);
    lv_obj_set_align(ui_buttonPvP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonPvP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonPvP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonPvP, lv_color_hex(0x1AAD19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonPvP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_home);
    lv_obj_set_width(ui_Button3, 180);
    lv_obj_set_height(ui_Button3, 60);
    lv_obj_set_x(ui_Button3, 200);
    lv_obj_set_y(ui_Button3, 120);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_home);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -151);
    lv_obj_set_y(ui_Label1, 119);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "P v P");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image1, &ui_img_home_2v2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image1, -250);
    lv_obj_set_y(ui_Image1, 120);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image2, &ui_img_home_cpu_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image2, 143);
    lv_obj_set_y(ui_Image2, 119);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 300);

    ui_Label2 = lv_label_create(ui_home);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 243);
    lv_obj_set_y(ui_Label2, 119);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, " vs AI");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image3, &ui_img_settings_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image3, 370);
    lv_obj_set_y(ui_Image3, -211);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 350);

    ui_Image30 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image30, &ui_img_814085921);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image30, 190);
    lv_obj_set_y(ui_Image30, -205);
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image30, 500);

    ui_Image31 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image31, &ui_img_1993502234);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image31, -47);
    lv_obj_set_y(ui_Image31, 165);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image31, 500);

    ui_Image32 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image32, &ui_img_1993502234);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image32, -357);
    lv_obj_set_y(ui_Image32, 166);
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image33 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image33, &ui_img_1993502234);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image33, 348);
    lv_obj_set_y(ui_Image33, 181);
    lv_obj_set_align(ui_Image33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image34 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image34, &ui_img_1993502234);
    lv_obj_set_width(ui_Image34, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image34, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image34, 54);
    lv_obj_set_y(ui_Image34, 116);
    lv_obj_set_align(ui_Image34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image34, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image34, 600);

    ui_Image35 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image35, &ui_img_1452054505);
    lv_obj_set_width(ui_Image35, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image35, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image35, 177);
    lv_obj_set_y(ui_Image35, -17);
    lv_obj_set_align(ui_Image35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image35, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image36 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image36, &ui_img_1452054505);
    lv_obj_set_width(ui_Image36, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image36, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image36, 228);
    lv_obj_set_y(ui_Image36, -17);
    lv_obj_set_align(ui_Image36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image36, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image37 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image37, &ui_img_1452054505);
    lv_obj_set_width(ui_Image37, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image37, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image37, 278);
    lv_obj_set_y(ui_Image37, -17);
    lv_obj_set_align(ui_Image37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image37, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image38 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image38, &ui_img_49543422);
    lv_obj_set_width(ui_Image38, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image38, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image38, 130);
    lv_obj_set_y(ui_Image38, -19);
    lv_obj_set_align(ui_Image38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image38, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image38, 450);

    ui_Image39 = lv_img_create(ui_home);
    lv_img_set_src(ui_Image39, &ui_img_1144387654);
    lv_obj_set_width(ui_Image39, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image39, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image39, -318);
    lv_obj_set_y(ui_Image39, 146);
    lv_obj_set_align(ui_Image39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image39, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image39, 400);

    ui_Label3 = lv_label_create(ui_home);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -221);
    lv_obj_set_y(ui_Label3, -92);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Two-player\n\n          card game");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonPvP, ui_event_buttonPvP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);

}
