// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_playPage2_screen_init(void)
{
    ui_playPage2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_playPage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_playPage2, &ui_img_play_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_playPage2);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -1273);
    lv_obj_set_y(ui_Button1, -661);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_playPage2);
    lv_img_set_src(ui_Image8, &ui_img_back_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image8, -363);
    lv_obj_set_y(ui_Image8, -203);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 350);

    ui_Image9 = lv_img_create(ui_playPage2);
    lv_img_set_src(ui_Image9, &ui_img_vs_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image9, -4);
    lv_obj_set_y(ui_Image9, -210);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_playPage2);
    lv_img_set_src(ui_Image10, &ui_img_famer_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image10, -64);
    lv_obj_set_y(ui_Image10, -214);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_playPage2);
    lv_img_set_src(ui_Image11, &ui_img_loader_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image11, 60);
    lv_obj_set_y(ui_Image11, -213);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image8, ui_event_Image8, LV_EVENT_ALL, NULL);

}
