// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_playPage1_screen_init(void)
{
    ui_playPage1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_playPage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_playPage1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_playPage1, &ui_img_play_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image4, &ui_img_back_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image4, -371);
    lv_obj_set_y(ui_Image4, -203);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 350);

    ui_Image6 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image6, &ui_img_loader_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image6, 53);
    lv_obj_set_y(ui_Image6, -212);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 220);

    ui_Image7 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image7, &ui_img_famer_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image7, -54);
    lv_obj_set_y(ui_Image7, -214);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image5, &ui_img_vs_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image5, -3);
    lv_obj_set_y(ui_Image5, -212);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_playPage1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image41 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image41, &ui_img_card_2_png);
    lv_obj_set_width(ui_Image41, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image41, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image41, 171);
    lv_obj_set_y(ui_Image41, -14);
    lv_obj_set_align(ui_Image41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image41, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image43 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image43, &ui_img_card_4_png);
    lv_obj_set_width(ui_Image43, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image43, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image43, 177);
    lv_obj_set_y(ui_Image43, 121);
    lv_obj_set_align(ui_Image43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image43, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image44 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image44, &ui_img_card_5_png);
    lv_obj_set_width(ui_Image44, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image44, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image44, -67);
    lv_obj_set_y(ui_Image44, -90);
    lv_obj_set_align(ui_Image44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image44, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image45 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image45, &ui_img_card_6_png);
    lv_obj_set_width(ui_Image45, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image45, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image45, 121);
    lv_obj_set_y(ui_Image45, -14);
    lv_obj_set_align(ui_Image45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image45, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image46 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image46, &ui_img_card_7_png);
    lv_obj_set_width(ui_Image46, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image46, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image46, 128);
    lv_obj_set_y(ui_Image46, 123);
    lv_obj_set_align(ui_Image46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image46, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image47 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image47, &ui_img_card_8_png);
    lv_obj_set_width(ui_Image47, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image47, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image47, 82);
    lv_obj_set_y(ui_Image47, -13);
    lv_obj_set_align(ui_Image47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image47, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image48 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image48, &ui_img_card_9_png);
    lv_obj_set_width(ui_Image48, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image48, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image48, 91);
    lv_obj_set_y(ui_Image48, 121);
    lv_obj_set_align(ui_Image48, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image48, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image40 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image40, &ui_img_card_1_png);
    lv_obj_set_width(ui_Image40, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image40, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image40, -239);
    lv_obj_set_y(ui_Image40, 99);
    lv_obj_set_align(ui_Image40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image40, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image42 = lv_img_create(ui_playPage1);
    lv_img_set_src(ui_Image42, &ui_img_card_3_png);
    lv_obj_set_width(ui_Image42, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_Image42, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image42, -122);
    lv_obj_set_y(ui_Image42, 121);
    lv_obj_set_align(ui_Image42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image42, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);

}
